Error: FORWARD_NULL gutenprint-5.2.6/src/main/print-list.c:352: var_compare_op: Comparing "name" to null implies that "name" might be null. gutenprint-5.2.6/src/main/print-list.c:385: var_deref_model: Passing null variable "name" to function "stp_list_get_item_by_name_internal", which dereferences it. gutenprint-5.2.6/src/main/print-list.c:333: deref_parm_in_call: Function "strcmp" dereferences parameter "name". (The dereference is assumed on the basis of the 'nonnull' parameter attribute.)
Error: FORWARD_NULL
gutenprint-5.2.6/src/main/print-list.c:426: var_compare_op: Comparing "long_name" to null implies that "long_name" might be null.
gutenprint-5.2.6/src/main/print-list.c:459: var_deref_model: Passing null variable "long_name" to function "stp_list_get_item_by_long_name_internal", which dereferences it.
gutenprint-5.2.6/src/main/print-list.c:407: deref_parm_in_call: Function "strcmp" dereferences parameter "long_name". (The dereference is assumed on the basis of the 'nonnull' parameter attribute.)

Error: FORWARD_NULL
gutenprint-5.2.6/src/main/escp2-driver.c:246: var_compare_op: Comparing "pd->input_slot" to null implies that "pd->input_slot" might be null.
gutenprint-5.2.6/src/main/escp2-driver.c:276: var_deref_op: Dereferencing null variable "pd->input_slot".

Error: FORWARD_NULL
gutenprint-5.2.6/src/main/module.c:96: var_compare_op: Comparing "module" to null implies that "module" might be null.
gutenprint-5.2.6/src/main/module.c:99: var_deref_op: Dereferencing null variable "module".

Error: FORWARD_NULL
gutenprint-5.2.6/src/main/print-canon.c:380: var_compare_op: Comparing "caps->paperlist" to null implies that "caps->paperlist" might be null.
gutenprint-5.2.6/src/main/print-canon.c:387: var_deref_op: Dereferencing null variable "caps->paperlist".

Error: FORWARD_NULL
gutenprint-5.2.6/src/main/print-color.c:1566: var_compare_op: Comparing "color_description" to null implies that "color_description" might be null.
gutenprint-5.2.6/src/main/print-color.c:1577: var_deref_op: Dereferencing null variable "color_description".

Error: FORWARD_NULL
gutenprint-5.2.6/src/main/print-escp2.c:1660: var_compare_op: Comparing "ink_list" to null implies that "ink_list" might be null.
gutenprint-5.2.6/src/main/print-escp2.c:1673: var_deref_op: Dereferencing null variable "ink_list".

Error: FORWARD_NULL
gutenprint-5.2.6/src/main/print-ps.c:826: var_compare_op: Comparing "node->child" to null implies that "node->child" might be null.
gutenprint-5.2.6/src/main/print-ps.c:841: var_deref_op: Dereferencing null variable "node->child".